import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { cn } from "../lib/utils";
import { Sidebar } from "../components/sidebar";
import Navbar from "../components/navbar";
import { Toaster } from "../components/ui/toaster";
import { ThemeProvider } from "../components/theme-provider";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Learn Acadamy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          inter.className
        )}
      >
        <ThemeProvider
          attribute="class"
          enableSystem
          defaultTheme="system"
        >
          <Navbar />
          <Sidebar />
          {children}
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
